---
- name: Update all Docker containers
  hosts: all  # Replace with the hostname or IP address of your Docker host
  become: yes  # Run tasks with sudo

  tasks:
    - name: Get a list of running Docker containers
      docker_container_info:
        filters:
          status: running
      register: running_containers

    - name: Update Docker containers
      docker_container:
        name: "{{ item.Name }}"
        image: "{{ item.Image }}"
        state: started
      loop: "{{ running_containers.containers }}"
