---
- name: Update Ubuntu
  hosts: all  # Replace with the hostname or IP address of your Ubuntu host
  become: yes  # Run tasks with sudo

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
