---
- name: Create folder in C:\temp
  hosts: windows_host  # Replace with the target Windows host(s)
  tasks:
    - name: Ensure C:\temp exists
      win_file:
        path: C:\temp
        state: directory
